### PR TITLE
Larafenny fastapi setup

### PR DESCRIPTION
**Pull request by larafenny**
In this PR, I made the following changes:
- Installed FastAPI and added initialization code in `main.py` to run the app
- Configured routing by setting the main router in `api.py` and added a test route in `test.py`
- Created a `Makefile` for setting up the virtual environment, installing dependencies, and running linting with `flake8`

### CODE REVIEW

**Review by francescosave — COMMENTED** [review]
```sh
HackathonTD@DESKTOP-AMEF271 MINGW64 ~/Desktop/Repo TeleCO2gram/backend (larafenny-fastapi-setup)
$ ./makefile
./makefile: line 2: create_venv:: command not found
0
(venv) 
HackathonTD@DESKTOP-AMEF271 MINGW64 ~/Desktop/Repo TeleCO2gram/backend (larafenny-fastapi-setup)
$
```
shell bash in so windows don't run correct this command of makefile (./Makefile).
Execute only command but don't interpred label command.
You should install Make or use only terminal command

Note
They are configurations for Windows systems

**Review by francescosave — COMMENTED** [review]
in so windows source use Script folder in venv 
python3.12 -m venv venv && source venv/Scripts/activate

source venv/bin/activate generate folder not found error.

image

Note
They are configurations for Windows systems

**Review by francescosave — COMMENTED** [review]
I have problem with uvloop dependecies

image

**Review by francescosave — APPROVED** [review]
The fastAPI server run ok

**Review by francescosave — APPROVED** [review]

**Review by marghe27 — APPROVED** [review]

**Pull request merged**
